# ----------------------------------------------------------------------------------------------
#  This is a work in progress. I am currently learning Github Actions yaml.
#  I'm bringing over the logic from azure-pipelines.yml
# ----------------------------------------------------------------------------------------------
name: Build & Publish AzDo Extension

env:
  EXTENSION_ID: pipelinesoverviewhub
  EXTENSION_NAME: dubsalot pipelines
  EXTENSION_ICON: logo.png
  EXTENSION_PIPELINE_ICON: pipeline-logo.png
  EXTENSION_HUBGROUP_ICON: logo-hub.png
  EXTENSION_PIPELINE_NAME: Pipeline Overview
  setPipelineVariables: replaceme
  BRANCH_NAME: replaceme
  NON_PROD_NAME: beta
  



# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop, feature/* ]
  #pull_request:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      EXTENSION_VERSION: ${{ steps.variables.outputs.extension_version }}
      NON_PROD_NAME: ${{ steps.variables.outputs.non_prod_name }}
    steps:
      - id: debug_output
        name: display debugging info - variables
        run: | 
          echo "github.action      : ${{ github.action	}}"
          echo "github.action_path : ${{ github.action_path}}"
          echo "github.actor       : ${{ github.actor}}"
          echo "github.base_ref    : ${{ github.base_ref}}"
          echo "github.event       : ${{ github.event}}"
          echo "github.event_name  : ${{ github.event_name}}"
          echo "github.event_path  : ${{ github.event_path}}"
          echo "github.head_ref    : ${{ github.head_ref	}}"
          echo "github.job         : ${{ github.job}}"          
          echo "github.ref         : ${{ github.ref }}"
          echo "github.sha         : ${{ github.sha }}"
          echo "github.run_number  : ${{ github.run_number }}"
          echo "github.token       : ${{ github.token }}"
          echo "github.workflow    : ${{ github.workflow }}"
          echo "github.workspace   : ${{ github.workspace }}"
      
      - id: set_alpha_if_feature
        if: ${{ startsWith(github.ref, 'refs/heads/feature') }}
        run: |
          echo set environment indicator to ALPHA
          echo "::set-output name=non_prod_name::alpha"

      - id: set_beta_if_develop
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          echo set environment indicator to BETA
          echo "::set-output name=non_prod_name::beta"          
        
      - id: variables
        run: | 
          echo "::set-output name=extension_version::$(date +"%Y.%m.%d").${{ github.run_id }}"

          
          
       
  # This workflow contains a single job called "build"
  build:
    name: "building ${{ needs.init.outputs.EXTENSION_VERSION }}"
    needs: init
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: also test here
        run: echo ${{ needs.init.outputs.EXTENSION_VERSION }}        


#give me some more whitespace
